# -*- coding: utf-8 -*-
"""FUTURE_ML_Task3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbGnBDVoTkK7qrwhJhIuHL9pCSVKY44y
"""

import pandas as pd

df = pd.read_csv("/content/Resume.csv")
df.head()

df.columns

df.info()

import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text

df.columns

import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text

df['clean_resume'] = df['Resume_str'].apply(clean_text)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')

X = vectorizer.fit_transform(df['clean_resume'])

X.shape

y = df['Category']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=300)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

df['score'] = model.predict_proba(X).max(axis=1)

df[['clean_resume', 'Category', 'score']].sort_values(by='score', ascending=False).head(10)